[package]
name = "d07"
version = "1.0.0"
authors = ["maislinger"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
